export default {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_ALL_COURSES: "GET_ALL_COURSES",
  GET_ALL_CLASSES: "GET_ALL_CLASSES",
  CREATE_COURSE: "CREATE_COURSE",
  CREATE_CLASS: "CREATE_CLASS"
};