export default {
  GET_TEST: "GET_TEST",
  GET_ALL_COURSES: "GET_ALL_COURSES",
  GET_ALL_CLASSES: "GET_ALL_CLASSES",
  CREATE_COURSE: "CREATE_COURSE",
  CREATE_CLASS: "CREATE_CLASS"
  /*GET_USER: "GET_USER"*/
};