export default {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_ALL_LECTURERS: "GET_ALL_LECTURERS",
  GET_ALL_COURSES: "GET_ALL_COURSES",
  GET_ALL_CLASSES: "GET_ALL_CLASSES",
  CREATE_COURSE: "CREATE_COURSE",
  CREATE_CLASS: "CREATE_CLASS",
  GET_ALL_FINAL_TASKS: "GET_ALL_FINAL_TASKS",
  GET_FINAL_TASK_BY_ID: "GET_FINAL_TASK_BY_ID",
  GET_ALL_RESEARCHES: "GET_ALL_RESEARCHES",
  GET_RESEARCH_BY_ID: "GET_RESEARCH_BY_ID",
  GET_ALL_JOURNALS: "GET_ALL_JOURNALS",
  GET_JOURNAL_BY_ID: "GET_RESEARCH_BY_ID"
};